<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Thorr\OAuth\Module'                                    => __DIR__ . '/src/Module.php',
  'Thorr\OAuth\Repository\UserRepositoryAwareTrait'       => __DIR__ . '/src/Repository/UserRepositoryAwareTrait.php',
  'Thorr\OAuth\Repository\UserRepositoryAwareInterface'   => __DIR__ . '/src/Repository/UserRepositoryAwareInterface.php',
  'Thorr\OAuth\Repository\UserRepositoryInterface'        => __DIR__ . '/src/Repository/UserRepositoryInterface.php',
  'Thorr\OAuth\Repository\Doctrine\UserRepositoryFactory' => __DIR__ . '/src/Repository/Doctrine/UserRepositoryFactory.php',
  'Thorr\OAuth\Repository\Doctrine\UserRepository'        => __DIR__ . '/src/Repository/Doctrine/UserRepository.php',
  'Thorr\OAuth\Entity\User'                               => __DIR__ . '/src/Entity/User.php',
  'Thorr\OAuth\Entity\UserTrait'                          => __DIR__ . '/src/Entity/UserTrait.php',
  'Thorr\OAuth\Entity\UserInterface'                      => __DIR__ . '/src/Entity/UserInterface.php',
  'Thorr\OAuth\Adapter\AdapterFactory'                    => __DIR__ . '/src/Adapter/AdapterFactory.php',
  'Thorr\OAuth\Adapter\Adapter'                           => __DIR__ . '/src/Adapter/Adapter.php',
  'Thorr\OAuth\Options\ModuleOptionsFactory'              => __DIR__ . '/src/Options/ModuleOptionsFactory.php',
  'Thorr\OAuth\Options\ModuleOptions'                     => __DIR__ . '/src/Options/ModuleOptions.php',
);
